### ISSUE TITLE
'Reconnect' command didn't work

### ISSUE THREAD

**Issue by ericmigi** [tulir/mautrix-whatsapp#142]
![Screenshot_20200213-143812_RiotX](https://user-images.githubusercontent.com/1048265/74503720-a64fb280-4ea6-11ea-8b67-aa4cdd2bf67b.jpg)

then this worked. Strange.

![Screenshot_20200213-143137_RiotX](https://user-images.githubusercontent.com/1048265/74503738-b7002880-4ea6-11ea-9123-28de7c49b006.jpg)

**Comment by vmario89** [comment]
hi, i have a similar issue for months now. It happens daily now which bugs me a lot:
![grafik](https://user-images.githubusercontent.com/5631071/75468206-21c46000-598d-11ea-8dcf-c8c1775e6865.png)

the behaviour: mautrix-whatsapp stops receiving messages but when typing "reconnect" it says its already connected. When typing "sync" it says "not connected". After this information and when sending "reconnect" again it says "reconnected succesfully".  Then it starts working again a short period :-/

**Comment by rreuvekamp** [comment]
I sometimes experience this as well.

This is what the logs show:

"""
2020-02-26-1.log-[Feb 26, 2020 19:15:30] [Command handler/DEBUG] @remi:remi.im sent 'Reconnect' in !mZLbsdQIrhbsRvaGKW:remi.im
2020-02-26-1.log:[Feb 26, 2020 19:15:30] [User/@remi:remi.im/WARN] Error while reconnecting: already logged in
2020-02-26-1.log:[Feb 26, 2020 19:15:30] [User/@remi:remi.im/DEBUG] Disconnecting due to failed session restore in reconnect command...
"""

It seems it's coming from:
https://github.com/tulir/mautrix-whatsapp/blob/691d2ea1b39176d322421e70827874e159d4cb8e/commands.go#L260

I guess the fix would be trying to reconnect if the session restore fails.
