### ISSUE TITLE
want to contribute to mautrix-whatsapp

### ISSUE THREAD

**Issue by pidongqianqian** [tulir/mautrix-whatsapp#190]
Hi, tulir
First of all, thank you for your open source library and your efforts. This library is really great. I want to make some contributions and have already done some work.

I don’t know if all the work I did meet the standards, but these functions have been tested.
These functions include group (invite / kick / join / create), location / contact message, etc.
For some reason, I did n’t submit a pr before, but I saw that you have updated a lot of things recently. Last Friday, I merged your updates into: [tulir-master](https://github.com/pidongqianqian/mautrix-whatsapp/tree/tulir-master).

If you have time, could you review it and give some advice? I will continue to merge your two-day updates to the above branch tomorrow. After I confirm that there is no conflict, I will submit pr as soon as possible.

**Comment by tulir** [comment]
Location messages need a `geo_uri` field. I just updated mautrix-go's MessageEventContent struct to support that, it's in v0.4.6: https://github.com/tulir/mautrix-go/commit/81fdb5caabfe4285a64abbbf85bab21fb55a8471. The value should be something like `geo:<latitude>,<longitude>` (the spec uses `geo:51.5008,0.1247` as an example)

Group management commands: it would be better to bridge Matrix invite/kick/leave instead of having separate commands to do it. Create and join can be commands since there's no really equivalent action in Matrix, although create should use the room name and member list instead of asking for phone numbers as arguments (so the flow would be: create room and set name, invite ghost users, run `!wa create` without arguments)

**Comment by pidongqianqian** [comment]
Thanks! I get it. what you said about group makes sense.
I will update in the near future, and then submit a pr

**Comment by PureTryOut** [comment]
Just a question, why not submit a PR now? It doesn't have to be ready, just mark it as WIP by appending WIP in front of the title. That is how basically all PR's work, and it allows for the discussion to stay on the relevant code, and even comment on the code directly using some fancy Github features.

**Comment by tulir** [comment]
> It doesn't have to be ready, just mark it as WIP by appending WIP in front of the title

GitHub has a proper draft PR thing nowadays: https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by keven99** [comment]
Would it be a good idea to re-implement "go-whatsapp" based on the protocol used by the yowsup library?

**Comment by tulir** [comment]
I think I ended up implementing most of the features myself. In the future, you should make smaller pull requests for one feature at a time so that it's easier to review and merge quickly instead of it getting stuck.

> Would it be a good idea to re-implement "go-whatsapp" based on the protocol used by the yowsup library?

No.

**Comment by pidongqianqian** [comment]
> I think I ended up implementing most of the features myself. In the future, you should make smaller pull requests for one feature at a time so that it's easier to review and merge quickly instead of it getting stuck.
> 
> > Would it be a good idea to re-implement "go-whatsapp" based on the protocol used by the yowsup library?
> 
> No.

yeah..ok, I have been entangled in other things since then, I should let you know as soon as possible, sorry for that, hope I didn’t disrupt your plan. anyway, good luck
