### ISSUE TITLE
A bunch of (new?) errors on startup with latest docker image

### ISSUE THREAD

**Issue by ptman** [tulir/mautrix-whatsapp#6]
```
[Sep  4, 2018 06:33:37] [Puppet/<phone-nr>@s.whatsapp.net/WARN] Failed to set display name: msg=Failed to POST JSON to /_matrix/client/r0/register code=400 wrapped=M_EXCLUSIVE: Invalid user localpart for this application service.
```

and

```
[Sep  4, 2018 06:33:37] [Puppet/<phone-nr>@s.whatsapp.net/ERROR] Failed to upload avatar: msg=Upload request failed: {"errcode":"M_FORBIDDEN","error":"Application service cannot masquerade as this user."} code=403 wrapped=
```

**Comment by fancypantalons** [comment]
To make this more concrete, I'm seeing a lot of these errors running Synapse 0.34.0 and... uh... the latest? version of mautrix-whatsapp (I can't find a clear version number reported anywhere, so I'm not sure where to include this information).

The error are consistently about an "Include user localpart for this application service".  It sure looks to me like the bot is trying to create portal rooms on the server that include the full "@s.whatsapp.net" qualified name of the user in question.  Unfortunately, Synapse sees that as a localpart and blows up, since that's not valid on any Matrix server.

Assuming I'm correct, the natural solution would be to remap the whatsapp JID to something Matrix will tolerate, such as stripping off the domain part or remapping the "@".

But that is, of course, an educated guess. :)

**Comment by tulir** [comment]
Are these errors still happening for someone?

**Comment by ptman** [comment]
I can no longer find these in my logs.
